name: Acceptance Test

on:
  workflow_call:

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Cache Images
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: /tmp/images
          key: ${{ runner.os }}-images-${{ github.run_id }}-${{ github.run_number }}
      - name: Restore images
        run: |
          docker load -i /tmp/images/s3-antivirus.tar
          docker load -i /tmp/images/s3-antivirus-update.tar
      - name: Run Acceptance Tests
        run: make acceptance-test
