name: Acceptance Test

on:
  workflow_call:

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Cache Images
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/images
          key: ${{ runner.os }}-images-${{ github.run_id }}-${{ github.run_number }}
      - name: Restore images
        run: |
          docker load -i /tmp/images/s3-antivirus.tar
          docker load -i /tmp/images/s3-antivirus-update.tar
      - name: Run Acceptance Tests
        run: make acceptance-test
