name: Create Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "Semver Tag (the latest tag on a workflow dispatch)"
        value: ${{ jobs.create_tag.outputs.tag }}
      timestamp:
        description: "timestamp"
        value: ${{ jobs.create_tag.outputs.timestamp }}

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: '0'

      - name: "Generate semver tag and release"
        id: semver_tag
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@c9c5dfb290b8f614df0884928c521165ba83d630 # v3.1.4
        with:
          releases_enabled: false
          with_v: true

      - name: Return latest tag
        id: latest_tag
        if: github.event_name == 'workflow_dispatch'
        uses: ministryofjustice/opg-github-actions/.github/actions/latest-tag@c9c5dfb290b8f614df0884928c521165ba83d630 # v3.1.4
        with:
          branch_name: ${{ github.event.workflow_dispatch.branch }}

      - name: Post tag to summary
        run: |
          if [ ${{ github.event_name }} == "workflow_dispatch" ]
          then
            tag=${{ steps.latest_tag.outputs.last_release }}
          else
            tag=${{ steps.semver_tag.outputs.created_tag }}
          fi
          echo "Tag: $tag" >> $GITHUB_STEP_SUMMARY
      - name: Set Timestamp
        id: timestamp
        run: echo "timestamp=$(date +"%Y%m%d%H%M%S")" >> "$GITHUB_OUTPUT"
    outputs:
      tag: |
        if [ ${{ github.event_name }} == "workflow_dispatch" ]
          then
            ${{ steps.latest_tag.outputs.last_release }}
          else
            ${{ steps.semver_tag.outputs.created_tag }}
          fi
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
