name: Docker Build

on:
  workflow_call:

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    env:
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Cache Images
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: /tmp/images
          key: ${{ runner.os }}-images-${{ github.run_id }}-${{ github.run_number }}
      - name: Build Images
        run: |
          make build
          mkdir -p /tmp/images
          docker save -o /tmp/images/s3-antivirus.tar 311462405659.dkr.ecr.eu-west-1.amazonaws.com/s3-antivirus:latest
          docker save -o /tmp/images/s3-antivirus-update.tar 311462405659.dkr.ecr.eu-west-1.amazonaws.com/s3-antivirus-update:latest
