name: Push Tags

on:
  workflow_call:
    inputs:
      tag:
        description: "Semver Tag"
        required: true
        type: string
      timestamp:
        description: "timestamp"
        required: true
        type: string

jobs:
  push-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure OIDC AWS credentials for SSM
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: arn:aws:iam::997462338508:role/sirius-component-ssm-role
          role-session-name: opg-sirius-lpa-dashboard-github-actions-ssm-push
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Push Tag to Parameter Store
        run: |
          aws ssm put-parameter --name "opg-s3-antivirus-latest-green-build" --type "String" --value "${{ inputs.tag }}" --overwrite --region=eu-west-1
