name: Push Tags

on:
  workflow_call:
    inputs:
      tag:
        description: "Semver Tag"
        required: true
        type: string
      timestamp:
        description: "timestamp"
        required: true
        type: string

jobs:
  push-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Configure OIDC AWS credentials for SSM
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::997462338508:role/sirius-component-ssm-role
          role-session-name: opg-sirius-lpa-dashboard-github-actions-ssm-push
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Push Tag to Parameter Store
        run: |
          aws ssm put-parameter --name "opg-s3-antivirus-latest-green-build" --type "String" --value "${{ inputs.tag }}" --overwrite --region=eu-west-1
