name: Push Tags

on:
  workflow_call:
    inputs:
      tag:
        description: "Semver Tag"
        required: true
        type: string
      timestamp:
        description: "timestamp"
        required: true
        type: string

jobs:
  push-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Configure OIDC AWS credentials for SSM
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: arn:aws:iam::997462338508:role/sirius-component-ssm-role
          role-session-name: opg-sirius-lpa-dashboard-github-actions-ssm-push
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Push Tag to Parameter Store
        run: |
          aws ssm put-parameter --name "opg-s3-antivirus-latest-green-build" --type "String" --value "${{ inputs.tag }}" --overwrite --region=eu-west-1
